try {
    console.log(naoexisto);
} catch(err) {
    console.log('naoexisto n√£o existe')
    console.log(err)
}